### ISSUE TITLE
Currency Selector

### ISSUE THREAD

**Issue by jonasW3F** [laboon/kraken_parser#1]
Great tool, thanks!

It would be great to add more currencies that staking rewards are denoted in. Most pressing one for me would be CHF but I guess many people would also appreciate Euro.

Thanks!

**Comment by laboon** [comment]
I am planning to add CHF and EUR compatibility. The interface will probably be something like "ruby token_parser.rb file.csv CHF".

**Comment by laboon** [comment]
Fixed by #2
